### ISSUE TITLE
[META] Purpose & Features

### ISSUE THREAD

**Issue by AJV009** [gpnagar/gpnagar.github.io#3]
## Features
- [ ] Integrate 'Google Firebase' for data management.
- [ ] Connect our Discord channel to send alerts on new events like repo PRs and new issues.
- [ ] Add an email subscription service like MailChimp to send bulk emails.
- [ ] Add another email service as simple as Gmail SMTP with JS to send quick emails or reminders.
- [ ] An option like on the organize.MLH site to add/remove, plan & share Events effectively with the resources and links.

The below thread will be used to discuss possible feature set and the main purpose of each. Come up with unique and feasible ideas. :smiley:
